apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: webapps
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80

    - host: email.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emailservice
                port:
                  number: 5000

    - host: check.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: checkoutservice
                port:
                  number: 5050

    - host: cart.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cart
                port:
                  number: 7070

    - host: pay.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paymentservice
                port:
                  number: 50051

    - host: ad.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: adservice
                port:
                  number: 9555

    - host: product.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: productcatalogservice
                port:
                  number: 3550

    - host: halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: recommendationservice
                port:
                  number: 8080

    - host: shipping.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: shippingservice
                port:
                  number: 50051

    - host: cur.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: currencyservice
                port:
                  number: 7000

    - host: load.halomedx.store
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: loadgenerator
                port:
                  number: 80
